// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_simple_bank.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName             string               `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PasswordChangedAt    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=password_changed_at,json=passwordChangedAt,proto3" json:"password_changed_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b64e86b71303064, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPasswordChangedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PasswordChangedAt
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b64e86b71303064, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b64e86b71303064, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b64e86b71303064, []int{3}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	User                  *User                `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId             string               `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken           string               `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string               `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b64e86b71303064, []int{4}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginUserResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *LoginUserResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginUserResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginUserResponse) GetAccessTokenExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.AccessTokenExpiresAt
	}
	return nil
}

func (m *LoginUserResponse) GetRefreshTokenExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.RefreshTokenExpiresAt
	}
	return nil
}

type NoParameterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParameterRequest) Reset()         { *m = NoParameterRequest{} }
func (m *NoParameterRequest) String() string { return proto.CompactTextString(m) }
func (*NoParameterRequest) ProtoMessage()    {}
func (*NoParameterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b64e86b71303064, []int{5}
}

func (m *NoParameterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParameterRequest.Unmarshal(m, b)
}
func (m *NoParameterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParameterRequest.Marshal(b, m, deterministic)
}
func (m *NoParameterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParameterRequest.Merge(m, src)
}
func (m *NoParameterRequest) XXX_Size() int {
	return xxx_messageInfo_NoParameterRequest.Size(m)
}
func (m *NoParameterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParameterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoParameterRequest proto.InternalMessageInfo

type GetAllUserResponse struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserResponse) Reset()         { *m = GetAllUserResponse{} }
func (m *GetAllUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllUserResponse) ProtoMessage()    {}
func (*GetAllUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b64e86b71303064, []int{6}
}

func (m *GetAllUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserResponse.Unmarshal(m, b)
}
func (m *GetAllUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserResponse.Marshal(b, m, deterministic)
}
func (m *GetAllUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserResponse.Merge(m, src)
}
func (m *GetAllUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllUserResponse.Size(m)
}
func (m *GetAllUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserResponse proto.InternalMessageInfo

func (m *GetAllUserResponse) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "pb.CreateUserResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "pb.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "pb.LoginUserResponse")
	proto.RegisterType((*NoParameterRequest)(nil), "pb.NoParameterRequest")
	proto.RegisterType((*GetAllUserResponse)(nil), "pb.GetAllUserResponse")
}

func init() { proto.RegisterFile("service_simple_bank.proto", fileDescriptor_4b64e86b71303064) }

var fileDescriptor_4b64e86b71303064 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xd3, 0xb4, 0x8a, 0x27, 0x45, 0x22, 0x4b, 0x02, 0xc1, 0xa5, 0x22, 0x98, 0x4b, 0x4e,
	0x8e, 0x14, 0x2e, 0x20, 0xb8, 0xa4, 0x15, 0x42, 0x54, 0xa8, 0x82, 0xa4, 0x5c, 0xb8, 0x58, 0x6b,
	0x67, 0x92, 0xac, 0x62, 0x7b, 0x97, 0xdd, 0x35, 0xf4, 0xc4, 0xb7, 0xc1, 0x7f, 0xf0, 0x31, 0xc8,
	0xbb, 0x76, 0xea, 0xc6, 0x87, 0xf6, 0xc0, 0x71, 0xde, 0xcc, 0xbc, 0xf7, 0xe6, 0x79, 0x0d, 0x4f,
	0x15, 0xca, 0x1f, 0x2c, 0xc6, 0x50, 0xb1, 0x54, 0x24, 0x18, 0x46, 0x34, 0xdb, 0x06, 0x42, 0x72,
	0xcd, 0x49, 0x4b, 0x44, 0xde, 0xf3, 0x35, 0xe7, 0xeb, 0x04, 0x27, 0x06, 0x89, 0xf2, 0xd5, 0x44,
	0xb3, 0x14, 0x95, 0xa6, 0xa9, 0xb0, 0x43, 0xfe, 0x5f, 0x07, 0xda, 0x5f, 0x15, 0x4a, 0xe2, 0x41,
	0x27, 0x57, 0x28, 0x33, 0x9a, 0xe2, 0xd0, 0x19, 0x39, 0x63, 0x77, 0xbe, 0xab, 0xc9, 0x09, 0xb8,
	0xab, 0x3c, 0x49, 0x42, 0xd3, 0x6c, 0xd9, 0x66, 0x01, 0x5c, 0x16, 0xcd, 0x3e, 0x1c, 0x62, 0x4a,
	0x59, 0x32, 0x3c, 0x30, 0x0d, 0x5b, 0x90, 0x0b, 0x78, 0x24, 0xa8, 0x52, 0x3f, 0xb9, 0x5c, 0x86,
	0xf1, 0x86, 0x66, 0x6b, 0x5c, 0x86, 0x54, 0x0f, 0xdb, 0x23, 0x67, 0xdc, 0x9d, 0x7a, 0x81, 0xb5,
	0x15, 0x54, 0xb6, 0x82, 0xab, 0xca, 0xd6, 0xbc, 0x57, 0xad, 0x9d, 0xdb, 0xad, 0x99, 0x26, 0x6f,
	0x00, 0x62, 0x89, 0x54, 0x5b, 0x8a, 0xc3, 0x3b, 0x29, 0xdc, 0x72, 0x7a, 0xa6, 0xfd, 0x5f, 0xd0,
	0x3b, 0x37, 0x45, 0x71, 0xe3, 0x1c, 0xbf, 0xe7, 0xa8, 0xf4, 0xff, 0x3e, 0xd5, 0x83, 0x4e, 0xe5,
	0xd9, 0xdc, 0xe7, 0xce, 0x77, 0xb5, 0x3f, 0x05, 0x52, 0xd7, 0x57, 0x82, 0x67, 0x0a, 0xc9, 0x33,
	0x68, 0x17, 0x82, 0x43, 0x67, 0x74, 0x30, 0xee, 0x4e, 0x3b, 0x81, 0x88, 0x02, 0xd3, 0x37, 0xa8,
	0x7f, 0x01, 0x0f, 0x3f, 0xf1, 0x35, 0xcb, 0xee, 0x6b, 0xb9, 0xae, 0xdf, 0xda, 0xd3, 0xff, 0xdd,
	0x82, 0x5e, 0x8d, 0xac, 0xa1, 0xef, 0x34, 0xf5, 0xc9, 0x29, 0x80, 0x42, 0xa5, 0x18, 0xcf, 0x42,
	0x56, 0x31, 0xba, 0x25, 0xf2, 0x71, 0x49, 0x5e, 0xc0, 0x31, 0x8d, 0x63, 0x54, 0x2a, 0xd4, 0x7c,
	0x8b, 0x59, 0x99, 0x45, 0xd7, 0x62, 0x57, 0x05, 0x44, 0x5e, 0xc2, 0x03, 0x89, 0x2b, 0x89, 0x6a,
	0x53, 0xce, 0xd8, 0x58, 0x8e, 0x4b, 0xd0, 0x0e, 0x7d, 0x81, 0x27, 0x75, 0x9e, 0x10, 0xaf, 0x05,
	0x93, 0xa8, 0xee, 0xf7, 0x89, 0xfb, 0x35, 0xb9, 0xf7, 0x76, 0x71, 0xa6, 0xc9, 0x02, 0x86, 0xb7,
	0x74, 0xeb, 0x9c, 0x47, 0x77, 0x72, 0x0e, 0xea, 0xf6, 0x76, 0xa4, 0x7e, 0x1f, 0xc8, 0x25, 0xff,
	0x4c, 0x25, 0x4d, 0x51, 0xef, 0x3e, 0x88, 0x3f, 0x06, 0xf2, 0x01, 0xf5, 0x2c, 0x49, 0x6e, 0x05,
	0x4b, 0x6a, 0xc1, 0xba, 0x36, 0xce, 0xe9, 0x1f, 0x07, 0x60, 0x61, 0x7e, 0xce, 0x33, 0x9a, 0x6d,
	0xc9, 0x5b, 0x80, 0x9b, 0x17, 0x41, 0x06, 0x45, 0xf6, 0x8d, 0x17, 0xea, 0x3d, 0xde, 0x87, 0x4b,
	0xfe, 0xd7, 0xe0, 0xda, 0xaf, 0xb9, 0x40, 0x49, 0xfa, 0xc5, 0xd0, 0xfe, 0x4b, 0xf1, 0x06, 0x7b,
	0x68, 0xb9, 0xf9, 0x0e, 0xe0, 0xc6, 0x2f, 0x31, 0xfc, 0xcd, 0xab, 0xac, 0x6e, 0xf3, 0xae, 0xb3,
	0xd3, 0x6f, 0x27, 0x9b, 0x5c, 0xe9, 0x78, 0xc3, 0x36, 0x0c, 0xf3, 0xc9, 0x5a, 0x8a, 0x38, 0xc4,
	0x6b, 0x5a, 0x1c, 0x35, 0x11, 0x51, 0x74, 0x64, 0xd2, 0x7c, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xb3, 0x25, 0x64, 0xd1, 0x8d, 0x04, 0x00, 0x00,
}
